<?php return array (
  'url' => 'http://example.com/',
  'domain' => 'example.com',
  'path' => '/',
  'assets' => '/assets/',
  'author' => 'https://devoldere.net',
  'logo' => 'assets/logo/logo.jpg',
  'favicon' => 'assets/logo/logo256.png',
  'bgVideo' => 'bg_video.mp4',
  'theme' => 'theme_name',
  'containerClass' => 'container',
  'themeColor' => '292E66',
  'themeColor2' => 'BD5D38',
  'title' => 'Bulb',
  'subtitle' => 'Example App',
  'description' => 'Bulb Example App description',
  'owner' => 'Your Name',
  'fullName' => 'Bulb Example App',
  'address' => '30 rue de Lille, 59000 Lille, FRANCE',
  'contactEmail' => 'email@example.com',
  'contactPhone' => '+33607080910',
  'facebook' => 'https://www.facebook.com/your_facebook_id/',
);